/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.view;

import game.bean.Invitation;
import game.bean.Team;
import game.controller.PlayerController;
import game.controller.TeamController;
import game.util.Util;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lucas
 */
public class InvitationChallenge extends javax.swing.JFrame {

    public Invitation invitation;
    public PlayerController controller;
    public TeamController teamController;
    public Team tm;
    public MainWindow window;

    /**
     * Creates new form IntationJoinTeam
     */
    public InvitationChallenge(PlayerController pc, TeamController tc, Invitation inv, MainWindow mw) {
        initComponents();
        this.controller = pc;
        this.teamController = tc;
        this.invitation = inv;
        this.window = mw;

        try {
            if (teamController.team.getID().equalsIgnoreCase(inv.getFrom())) {
                tm = controller.factory.getAuthenticationInterface().getTeam(inv.getTo());
                msg.setText("Your team will challenge "+inv.getPoints()+" points with the team '" + tm.getName() + "'. Do you will accept?");
            } else {
                tm = controller.factory.getAuthenticationInterface().getTeam(inv.getFrom());
                msg.setText("The team '" + tm.getName() + "' is challenging "+inv.getPoints()+" points with your team. Do you will accept?");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(InvitationChallenge.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msg = new javax.swing.JLabel();
        accep = new javax.swing.JButton();
        rej = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msg.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg.setText("jLabel1");

        accep.setText("Accept");
        accep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accepActionPerformed(evt);
            }
        });

        rej.setText("Reject");
        rej.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(accep, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rej, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accep, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rej, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accepActionPerformed
        try {
            invitation.setAnswer(Util.INVITATION_ACCEPTED);
            if (teamController.team.getID().equalsIgnoreCase(invitation.getFrom())) {
                controller.factory.getInvitationChallengeInterface().answerInternalInvitation(invitation);
            } else {
                controller.factory.getInvitationChallengeInterface().answerExternalInvitation(invitation);
            }
            controller.sendMessageTeam(controller.player.getName() + " accepted the challenge", teamController.team);

        } catch (RemoteException ex) {
            Logger.getLogger(InvitationChallenge.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();

    }//GEN-LAST:event_accepActionPerformed

    private void rejActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejActionPerformed
         try {
            invitation.setAnswer(Util.INVITATION_REJECTED);
            if (teamController.team.getID().equalsIgnoreCase(invitation.getFrom())) {
                controller.factory.getInvitationChallengeInterface().answerInternalInvitation(invitation);
            } else {
                controller.factory.getInvitationChallengeInterface().answerExternalInvitation(invitation);
            }
            controller.sendMessageTeam(controller.player.getName() + " rejected the challenge", teamController.team);

        } catch (RemoteException ex) {
            Logger.getLogger(InvitationChallenge.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_rejActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accep;
    private javax.swing.JLabel msg;
    private javax.swing.JButton rej;
    // End of variables declaration//GEN-END:variables
}
