/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game.view;

import game.controller.TeamController;
import java.awt.event.KeyEvent;

/**
 *
 * @author Lucas
 */
public class NewTeam extends javax.swing.JFrame {
    
    private final TeamController teamController;
     private final MainWindow parent;

    /**
     * Creates new form NewTeam
     * @param teamController
     * @param parent
     */
    public NewTeam(TeamController teamController,MainWindow parent) {
        initComponents();
         this.teamController = teamController;
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jtTeamName = new javax.swing.JTextField();
        jbJdNewTeamOK = new javax.swing.JButton();
        jlErrorNT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Team");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 0, 20)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Please, Enter with a Team's name:");

        jtTeamName.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jtTeamName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtTeamName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtTeamNameKeyPressed(evt);
            }
        });

        jbJdNewTeamOK.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jbJdNewTeamOK.setText("OK");
        jbJdNewTeamOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJdNewTeamOKActionPerformed(evt);
            }
        });

        jlErrorNT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlErrorNT.setForeground(new java.awt.Color(204, 0, 0));
        jlErrorNT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlErrorNT, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(173, 173, 173)
                                    .addComponent(jbJdNewTeamOK))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addComponent(jtTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtTeamName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jbJdNewTeamOK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlErrorNT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtTeamNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtTeamNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String teamName = jtTeamName.getText();
            if (!teamController.checkTeam(teamName)) {
                teamController.createTeam(teamName);
                parent.setTeam();
                this.dispose();
            } else {
                jlErrorNT.setText("This Team's name already exist!");
            }
        }
    }//GEN-LAST:event_jtTeamNameKeyPressed

    private void jbJdNewTeamOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJdNewTeamOKActionPerformed
        String teamName = jtTeamName.getText();
        if (!teamController.checkTeam(teamName)) {
            teamController.createTeam(teamName);
            parent.setTeam();
            this.dispose();
        } else {
            jlErrorNT.setText("This Team's name already exist!");
        }
    }//GEN-LAST:event_jbJdNewTeamOKActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbJdNewTeamOK;
    private javax.swing.JLabel jlErrorNT;
    private javax.swing.JTextField jtTeamName;
    // End of variables declaration//GEN-END:variables
}
